"""
Description: 
    Generates the values for 'Table 3.2: Descriptive Statistics of Target Fitness Metrics'.
    It aggregates fitness metrics for the UKBB cohort and produces a TableOne summary.

Output: 
    Saves a LaTeX file with the summary statistics.
    
Note on Formatting:
    The LaTeX output generated by this script contains the raw values used in the report.
    Final visual adjustments (formatting, column widths, caption styling) were applied 
    manually in Overleaf.
"""

from tableone import TableOne
import pandas as pd
import numpy as np
import os
import re

LABELS_BASE_DIR = "/cluster/work/grlab/projects/tmp_imankowski/data/labels/real_ukbb_values/" 
RESTING_ECG_PATH = "/cluster/work/grlab/projects/projects2025-dataspectrum4cvd/ukbb/raw/Bulk/ECG"
OUTPUT_DIR = "/cluster/work/grlab/projects/tmp_imankowski/data/analysis_dec_summarised/"

FITNESS_TASKS = {
    'VO2max_i1': {'id': '30038-1.0', 'path': os.path.join(LABELS_BASE_DIR, "30038-1.0.csv")},
    'VO2max_i0': {'id': '30038-0.0', 'path': os.path.join(LABELS_BASE_DIR, "30038-0.0.csv")},
    'Walking_Pace': {'id': '924-2.0', 'path': os.path.join(LABELS_BASE_DIR, "924-2.0.csv")},
    'Able_To_Walk_10Min': {'id': '6017-1.0', 'path': os.path.join(LABELS_BASE_DIR, "6017-1.0.csv")},
    'LVEF': {'id': '31060-2.0', 'path': os.path.join(LABELS_BASE_DIR, "31060-2.0.csv")},
    'Systolic_BP': {'id': 'SYSTOLIC_BP_mean', 'path': os.path.join(LABELS_BASE_DIR, "SYSTOLIC_BP_mean.csv")},
    'Diastolic_BP': {'id': 'DIASTOLIC_BP_mean', 'path': os.path.join(LABELS_BASE_DIR, "DIASTOLIC_BP_mean.csv")},
    'Grip_Strength_Left': {'id': '46-2.0', 'path': os.path.join(LABELS_BASE_DIR, "46-2.0.csv")},
    'Grip_Strength_Right': {'id': '47-2.0', 'path': os.path.join(LABELS_BASE_DIR, "47-2.0.csv")},
    'Heel_Bone_T_Score': {'id': '78-0.0', 'path': os.path.join(LABELS_BASE_DIR, "78-0.0.csv")},
    'Heel_Bone_Density_Left': {'id': '4106-2.0', 'path': os.path.join(LABELS_BASE_DIR, "4106-2.0.csv")},
    'Body_Fat_Percentage': {'id': '23099-2.0', 'path': os.path.join(LABELS_BASE_DIR, "23099-2.0.csv")},
    'Whole_Body_Fat_Mass': {'id': '23100-2.0', 'path': os.path.join(LABELS_BASE_DIR, "23100-2.0.csv")},
    'Trunk_Fat_Percentage': {'id': '23127-2.0', 'path': os.path.join(LABELS_BASE_DIR, "23127-2.0.csv")},
    'Trunk_Fat_Mass': {'id': '23128-2.0', 'path': os.path.join(LABELS_BASE_DIR, "23128-2.0.csv")},
    'FEV1_best_i0': {'id': '20150-0.0', 'path': os.path.join(LABELS_BASE_DIR, "20150-0.0.csv")},
    'FEV1_i2': {'id': '3063-2.0', 'path': os.path.join(LABELS_BASE_DIR, "3063-2.0.csv")},
    'Forced_Vital_Capacity': {'id': '3062-2.0', 'path': os.path.join(LABELS_BASE_DIR, "3062-2.0.csv")},
    'FEV1_Predicted': {'id': '20153-0.0', 'path': os.path.join(LABELS_BASE_DIR, "20153-0.0.csv")},
    'FEV1_Predicted_Percentage': {'id': '20154-0.0', 'path': os.path.join(LABELS_BASE_DIR, "20154-0.0.csv")},
    'FEV1_Z_Score': {'id': '20256-0.0', 'path': os.path.join(LABELS_BASE_DIR, "20256-0.0.csv")},
    'FEV1_FVC_Ratio_Z': {'id': '20258-0.0', 'path': os.path.join(LABELS_BASE_DIR, "20258-0.0.csv")},
    'Tiredness_Freq': {'id': '2080-2.0', 'path': os.path.join(LABELS_BASE_DIR, "2080-2.0.csv")},
    'Reaction_Time': {'id': '20023-2.0', 'path': os.path.join(LABELS_BASE_DIR, "20023-2.0.csv")},
    'Health_Scale_Today': {'id': '120103-0.0', 'path': os.path.join(LABELS_BASE_DIR, "120103-0.0.csv")},
    'Health_Score_England': {'id': '26413-0.0', 'path': os.path.join(LABELS_BASE_DIR, "26413-0.0.csv")},
    'Health_Score_Scotland': {'id': '26420-0.0', 'path': os.path.join(LABELS_BASE_DIR, "26420-0.0.csv")},
    'Health_Score_Wales': {'id': '26430-0.0', 'path': os.path.join(LABELS_BASE_DIR, "26430-0.0.csv")}
}

DISPLAY_NAMES = {
    'VO2max_i1': '$\\dot{\\text{V}}\\text{O}_{2\\max}$ (inst. 1) (ml/kg/min)',
    'VO2max_i0': '$\\dot{\\text{V}}\\text{O}_{2\\max}$ (inst. 0) (ml/kg/min)',
    'Grip_Strength_Left': 'Grip Strength Left (kg)',
    'Grip_Strength_Right': 'Grip Strength Right (kg)',
    'Walking_Pace': 'Walking Pace (cat)',
    'Heel_Bone_T_Score': 'Heel Bone Mineral Density (T-Score)',
    'Heel_Bone_Density_Left': 'Heel Bone Density (g/cm$^2$)',
    'Body_Fat_Percentage': 'Body Fat Percentage (\%)',
    'Whole_Body_Fat_Mass': 'Whole Body Fat Mass (kg)',
    'Trunk_Fat_Percentage': 'Trunk Fat Percentage (\%)',
    'Trunk_Fat_Mass': 'Trunk Fat Mass (kg)',
    'FEV1_best_i0': 'FEV1 (L) (inst. 0)',
    'FEV1_i2': 'FEV1 (L) (inst. 2)',
    'Forced_Vital_Capacity': 'FVC (L)',
    'FEV1_Predicted': 'FEV1 Predicted (L)',
    'FEV1_Predicted_Percentage': 'FEV1 Predicted \%',
    'FEV1_Z_Score': 'FEV1 Z-Score',
    'FEV1_FVC_Ratio_Z': 'FEV1/FVC Ratio Z',
    'Able_To_Walk_10Min': 'Able to Walk 10min (cat)',
    'LVEF': 'LVEF (\%)',
    'Systolic_BP': 'Systolic Blood Pressure (mmHg)',
    'Diastolic_BP': 'Diastolic Blood Pressure (mmHg)',
    'Tiredness_Freq': 'Freq. of Tiredness (cat)',
    'Reaction_Time': 'Reaction Time (ms)',
    'Health_Scale_Today': 'Subj. Health Scale',
    'Health_Score_England': 'Health Score (Eng)',
    'Health_Score_Scotland': 'Health Score (Scot)',
    'Health_Score_Wales': 'Health Score (Wal)'
}

# -------------------- 1. Get eIDs from resting ECGs --------------------
xml_files = [f for f in os.listdir(RESTING_ECG_PATH) if f.endswith('.xml')]
eids_set = set()
for filename in xml_files:
    match = re.match(r'(\d{7})', filename)
    if match:
        eids_set.add(int(match.group(1)))

print(f'Extracted {len(eids_set)} unique eIDs from resting ECG XML filenames.')


# -------------------- 2. Load & Merge Fitness Metrics --------------------
# Initialize dataframe with ONLY the EIDs from the ECG folder 

data = pd.DataFrame(list(eids_set), columns=['eid'])

print("Loading fitness metrics...")

for metric_name, info in FITNESS_TASKS.items():
    csv_path = info['path']
    if os.path.exists(csv_path):
        temp_df = pd.read_csv(csv_path)
        
        if 'eid' in temp_df.columns:
            temp_df = temp_df.drop_duplicates(subset='eid')
            target_col = info['id'] if info['id'] in temp_df.columns else None
            
            if target_col:
                temp_df = temp_df[['eid', target_col]].rename(columns={target_col: metric_name})
                data = pd.merge(data, temp_df, on='eid', how='left')
            else:
                print(f"Warning: Could not identify value column for {metric_name} in {csv_path}")
        else:
            print(f"Warning: 'eid' column missing in {csv_path}")
    else:
        print(f"Warning: File not found for {metric_name}: {csv_path}")

print(f"Final data shape after merging metrics: {data.shape}")


# -------------------- 3. Prepare TableOne Variables --------------------

cohort_label_overall = 'no VO2max at I1'
cohort_label_subset = 'VO2max I1 Subset'

data['Analysis Cohort'] = cohort_label_overall
if 'VO2max_i1' in data.columns:
    has_vo2 = data['VO2max_i1'].notna()
    data.loc[has_vo2, 'Analysis Cohort'] = cohort_label_subset

data.rename(columns=DISPLAY_NAMES, inplace=True)

categorical_vars = []
continuous_vars = []

for key, display_name in DISPLAY_NAMES.items():
    if display_name not in data.columns:
        continue 
        
    if '(cat)' in display_name:
        categorical_vars.append(display_name)
    else:
        continuous_vars.append(display_name)

display_columns = categorical_vars + continuous_vars
display_columns = list(dict.fromkeys(display_columns))


# -------------------- 4. Generate TableOne --------------------
mytable = TableOne(
    data,
    columns=display_columns,
    categorical=categorical_vars,
    continuous=continuous_vars,
    groupby='Analysis Cohort',
    overall=True,
    pval=False,
    missing=True
)

print("\n--- TableOne Summary (Fitness Metrics Only) ---")
print(mytable.tabulate(tablefmt="github"))

latex_output_path = os.path.join(OUTPUT_DIR, 'tableone_fitness_metrics_only_final.tex')
latex_code = mytable.to_latex(
    caption="Baseline Characteristics (Fitness Metrics)",
    label="tab:fitness_only",
)

with open(latex_output_path, 'w') as f:
    f.write(latex_code)

print(f"\nLaTeX code saved to: {latex_output_path}")
